import type { Metadata } from "next";
import "./globals.css";
import ClientWrapper from "@/components/pages/ClientWrapper";
import { Suspense } from "react";
export const metadata: Metadata = {
  title: "Gastuin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body>
        <ClientWrapper>
          <Suspense>{children}</Suspense>{" "}
        </ClientWrapper>
        <div className="modal-container"></div>
      </body>
    </html>
  );
}
